### ISSUE TITLE
ClientError Invalid input

### ISSUE THREAD

**Issue by nboubakr** [vmapps/attack2neo#4]
Hello,

I faced a ClientError while trying to execute the script:

```
> python attack2neo.py --debug -f mitre-enterprise-attack.json --groups --softwares --tools --techniques --relations
Technique: "Password Filter DLL Mitigation"
Technique: "Space after Filename Mitigation"
Technique: "HISTCONTROL Mitigation"
Technique: "Credentials in Files Mitigation"
[...]
Group: "APT34"
Traceback (most recent call last):
  File "attack2neo.py", line 160, in <module>
    build_relations(obj)
  File "attack2neo.py", line 69, in build_relations
    source = m.match( build_label(obj['source_ref']), name=gnames[obj['source_ref']] ).first()
  File "Python310\lib\site-packages\py2neo\matching.py", line 94, in first
    return self.graph.evaluate(*self._query_and_parameters())
  File "Python310\lib\site-packages\py2neo\database.py", line 395, in evaluate
    return self.begin(autocommit=True).evaluate(cypher, parameters, **kwparameters)
  File "Python310\lib\site-packages\py2neo\database.py", line 876, in evaluate
    return self.run(cypher, parameters, **kwparameters).evaluate(0)
  File "Python310\lib\site-packages\py2neo\database.py", line 823, in run
    return Cursor(self.connector.run(statement=cypher,
  File "Python310\lib\site-packages\py2neo\internal\connectors.py", line 292, in run
    return self._run_1(statement, parameters, graph, keys, entities)
  File "Python310\lib\site-packages\py2neo\internal\connectors.py", line 255, in _run_1
    cx.fetch()
  File "Python310\lib\site-packages\neobolt\direct.py", line 422, in fetch
    return self._fetch()
  File "Python310\lib\site-packages\neobolt\direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "Python310\lib\site-packages\neobolt\direct.py", line 755, in on_failure
    handler(metadata)
  File "Python310\lib\site-packages\py2neo\internal\connectors.py", line 288, in _fail
    raise GraphError.hydrate(metadata)
py2neo.database.ClientError: SyntaxError: Invalid input '{': expected "+" or "-" (line 1, column 35 (offset: 34))
"MATCH (_:Software) WHERE _.name = {1} RETURN _"
```

I tried to install py2neo==5.0b1, but the version is not available:

```
> pip install py2neo==5.0b1
ERROR: Could not find a version that satisfies the requirement py2neo==5.0b1 (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1, 2021.1.0, 2021.1.1, 2021.1.2, 2021.1.3, 2021.1.4, 2021.1.5, 2021.2.0, 2021.2.1, 2021.2.2, 2021.2.3)
ERROR: No matching distribution found for py2neo==5.0b1
```

**Comment by nboubakr** [comment]
The issue has been solved by upgrading py2neo:

`> pip install --upgrade py2neo`
